"""Add fields energy and bandwith

Revision ID: 719f83ae73e5
Revises: a8f12746dc76
Create Date: 2025-04-17 14:29:35.993133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719f83ae73e5'
down_revision: Union[str, None] = 'a8f12746dc76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tronrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bandwidth', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('energy_remaining', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tronrequest', schema=None) as batch_op:
        batch_op.drop_column('energy_remaining')
        batch_op.drop_column('bandwidth')

    # ### end Alembic commands ###
