"""Add fields balance

Revision ID: f977ca85b7b5
Revises: 719f83ae73e5
Create Date: 2025-04-17 14:32:14.408658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f977ca85b7b5'
down_revision: Union[str, None] = '719f83ae73e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tronrequest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tronrequest', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
